# Formats the guides for the website from the rdoc pages generated by the
# website_rdoc_main rake task, wrapping the content of each rdoc page in the
# website's layout.
# All paths are relative to the directory containing the Rakefile.

require 'erb'

class MakeGuides
  LAYOUT_FILE = 'www/layout.html.erb'
  CONTENT = %r{<div id='content'>.*?(?=<div id='footer-push'>)}m

  # guide_dir  : the directory the guides are written to
  # rdoc_pages : the paths of the rdoc pages to make the guides from
  # main_page  : the path of the rdoc page for the front page guide
  def initialize(guide_dir, rdoc_pages, main_page)
    @guide_dir = guide_dir
    @public_dir = File.dirname(guide_dir)
    @layout = ERB.new(File.read(LAYOUT_FILE))
    @main_page = main_page
    @rdoc_pages = [main_page] + rdoc_pages
  end

  def execute
    @rdoc_pages.each{|rdoc_page| write_guide(rdoc_page)}
  end

  private

  def guide_path(rdoc_page)
    name = if rdoc_page == @main_page
             'README.html'
           else
              File.basename(rdoc_page).sub(/_rdoc\.html\z/, '.html')
           end
    File.join(@guide_dir, name)
  end

  def url(path)
    path.sub(/\A#{@public_dir}/, '')
  end

  def write_guide(rdoc_page)
    unless (body = File.read(rdoc_page)[CONTENT])
      raise "no content found in #{rdoc_page}, it was not generated by the hanna formatter"
    end

    guide = guide_path(rdoc_page)
    content = update_relative_links(body, File.dirname(rdoc_page))
    File.open(guide, 'wb'){|f| f.write(@layout.result_with_hash({content:, :stylesheet=>'guide', :title=>guide_title(guide, content)}))}
  end

  def guide_title(guide, content)
    return if File.basename(guide) == 'README.html'

    heading = content[%r{<h1[^>]*>(.*?)</h1>}m, 1]
    heading && heading.gsub(/<[^>]*>/, '').strip
  end

  def update_relative_links(html, rdoc_dir)
    html.gsub(/\b(href|src)=('|")([^'"]*)\2/) do
      "#{$1}=#{$2}#{update_relative_link($3, rdoc_dir)}#{$2}"
    end
  end

  def update_relative_link(link, rdoc_dir)
    return link if link.empty? || link.start_with?('#', '/') || link =~ /\A[a-z][a-z0-9+.-]*:/i

    path, fragment = link.split('#', 2)
    return link if path.nil? || path.empty?

    target = File.expand_path(path, url(rdoc_dir))
    rdoc_page = @rdoc_pages.find{|p| url(p) == target}
    target = url(guide_path(rdoc_page)) if rdoc_page

    fragment ? "#{target}##{fragment}" : target
  end
end
